title: Francois El-Daher
baseURL: "https://feldaher.github.io/"
languageCode: "en-us"
theme: [] # No theme, using custom layouts

enableEmoji: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

# Preserving taxonomies for content organization
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

# Simple permalinks
permalinks:
  publication_types: "/publication-type/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true
